<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\StudyProgram;
use App\Models\Degree;
use App\Models\Faculty;

class StudyProgramSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                "id" => Str::uuid()->toString(),
                "code" => 10124,
                "name" => "Manajemen Pendidikan",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 10224,
                "name" => "Pendidikan Luar Sekolah",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 10324,
                "name" => "Pendidikan Luar Biasa",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 10325,
                "name" => "Manajemen Pendidikan",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 10424,
                "name" => "Bimbingan dan Konseling",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 10425,
                "name" => "Pendidikan Luar Sekolah",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 10426,
                "name" => "Manajemen Pendidikan",
                "degree_id" => Degree::where('code', '=', '6')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 10524,
                "name" => "Teknologi Pendidikan",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 10725,
                "name" => "Teknologi Pembelajaran",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 10824,
                "name" => "Pendidikan Guru Sekolah Dasar",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 11024,
                "name" => "Kebijakan Pendidikan",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 11124,
                "name" => "Pendidikan Guru Pendidikan Anak Usia Dini",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 11214,
                "name" => "Psikologi",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 11225,
                "name" => "Pendidikan Dasar",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 11325,
                "name" => "Bimbingan dan Konseling",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 11725,
                "name" => "Pendidikan Anak Usia Dini",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 12925,
                "name" => "Pendidikan Luar Biasa",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 13125,
                "name" => "Psikologi",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '1')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 20124,
                "name" => "Pendidikan Bahasa dan Sastra Indonesia",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '2')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 20224,
                "name" => "Pendidikan Bahasa Inggris",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '2')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 20324,
                "name" => "Pendidikan Bahasa Jerman",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '2')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 20424,
                "name" => "Pendidikan Bahasa Perancis",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '2')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 20524,
                "name" => "Pendidikan Bahasa Jawa",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '2')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 20526,
                "name" => "Ilmu Pendidikan Bahasa",
                "degree_id" => Degree::where('code', '=', '6')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '2')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 20624,
                "name" => "Pendidikan Seni Rupa",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '2')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 20625,
                "name" => "Linguistik Terapan",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '2')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 20724,
                "name" => "Pendidikan Kriya",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '2')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 20824,
                "name" => "Pendidikan Seni Musik",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '2')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 20924,
                "name" => "Pendidikan Seni Tari",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '2')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 21014,
                "name" => "Sastra Indonesia",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '2')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 21114,
                "name" => "Sastra Inggris",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '2')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 21425,
                "name" => "Pendidikan Bahasa Jawa",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '2')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 21525,
                "name" => "Pendidikan Bahasa dan Sastra Indonesia",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '2')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 21625,
                "name" => "Pendidikan Bahasa Inggris",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '2')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 22425,
                "name" => "Pendidikan Seni",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '2')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 30124,
                "name" => "Pendidikan Matematika",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '3')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 30224,
                "name" => "Pendidikan Fisika",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '3')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 30324,
                "name" => "Pendidikan Kimia",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '3')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 30424,
                "name" => "Pendidikan Biologi",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '3')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 30514,
                "name" => "Matematika",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '3')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 30614,
                "name" => "Fisika",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '3')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 30714,
                "name" => "Kimia",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '3')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 30814,
                "name" => "Biologi",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '3')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 30825,
                "name" => "Pendidikan Sains",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '3')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 30914,
                "name" => "Statistika",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '3')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 30925,
                "name" => "Pendidikan Matematika",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '3')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 31224,
                "name" => "Pendidikan IPA",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '3')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 32525,
                "name" => "Pendidikan Biologi",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '3')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 32625,
                "name" => "Pendidikan Fisika",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '3')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 32825,
                "name" => "Pendidikan Kimia",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '3')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 40124,
                "name" => "Pendidikan Pancasila dan Kewarganegaraan",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '4')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 40524,
                "name" => "Pendidikan Geografi",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '4')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 40525,
                "name" => "Pendidikan Ilmu Pengetahuan Sosial",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '4')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 40624,
                "name" => "Pendidikan Sejarah",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '4')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 40714,
                "name" => "Ilmu Sejarah",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '4')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 41324,
                "name" => "Pendidikan Sosiologi",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '4')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 41624,
                "name" => "Pendidikan Ilmu Pengetahuan Sosial",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '4')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 41714,
                "name" => "Administrasi Publik",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '4')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 41825,
                "name" => "Pendidikan Sejarah",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '4')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 41914,
                "name" => "Ilmu Komunikasi",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '4')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 42725,
                "name" => "Pendidikan Geografi",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '4')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 43025,
                "name" => "Pendidikan Pancasila dan Kewarganegaraan",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '4')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 50124,
                "name" => "Pendidikan Teknik Elektro",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 50224,
                "name" => "Pendidikan Teknik Elektronika",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 50324,
                "name" => "Pendidikan Teknik Mesin",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 50424,
                "name" => "Pendidikan Teknik Otomotif",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 50524,
                "name" => "Pendidikan Teknik Sipil dan Perencanaan",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 50633,
                "name" => "Teknik Elektro",
                "degree_id" => Degree::where('code', '=', '3')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 50733,
                "name" => "Teknik Elektronika",
                "degree_id" => Degree::where('code', '=', '3')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 50833,
                "name" => "Teknik Mesin",
                "degree_id" => Degree::where('code', '=', '3')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 50933,
                "name" => "Teknik Otomotif",
                "degree_id" => Degree::where('code', '=', '3')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 51033,
                "name" => "Teknik Sipil",
                "degree_id" => Degree::where('code', '=', '3')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 51124,
                "name" => "Pendidikan Tata Boga",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 51233,
                "name" => "Teknik Boga",
                "degree_id" => Degree::where('code', '=', '3')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 51324,
                "name" => "Pendidikan Tata Busana",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 51433,
                "name" => "Teknik Busana",
                "degree_id" => Degree::where('code', '=', '3')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 51824,
                "name" => "Pendidikan Teknik Mekatronika",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 51933,
                "name" => "Tata Rias dan Kecantikan",
                "degree_id" => Degree::where('code', '=', '3')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 52024,
                "name" => "Pendidikan Teknik Informatika",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 52025,
                "name" => "Pendidikan Teknik Elektronika dan Informatika",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 52125,
                "name" => "Pendidikan Teknik Elektro",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 52225,
                "name" => "Pendidikan Teknik Mesin",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 52325,
                "name" => "Pendidikan Kesejahteraan Keluarga",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 53319,
                "name" => "Program Profesi Insinyur",
                "degree_id" => Degree::where('code', '=', '9')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 53714,
                "name" => "Teknologi Informasi",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 53814,
                "name" => "Teknik Elektro",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 53914,
                "name" => "Teknik Manufaktur",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 54014,
                "name" => "Teknik Sipil",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '5')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 60124,
                "name" => "Pendidikan Jasmani, Kesehatan, dan Rekreasi",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '6')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 60133,
                "name" => "Pengobatan Tradisional",
                "degree_id" => Degree::where('code', '=', '3')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '6')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 60224,
                "name" => "Pendidikan Kepelatihan Olahraga",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '6')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 60233,
                "name" => "Pengelolaan Usaha Rekreasi",
                "degree_id" => Degree::where('code', '=', '3')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '6')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 60314,
                "name" => "Ilmu Keolahragaan",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '6')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 60333,
                "name" => "Promosi Kesehatan",
                "degree_id" => Degree::where('code', '=', '3')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '6')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 60422,
                "name" => "Pendidikan Jasmani Sekolah Dasar",
                "degree_id" => Degree::where('code', '=', '2')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '6')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 60425,
                "name" => "Pendidikan Jasmani Sekolah Dasar",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '6')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 60826,
                "name" => "Ilmu Keolahragaan",
                "degree_id" => Degree::where('code', '=', '6')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '6')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 61125,
                "name" => "Ilmu Keolahragaan",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '6')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 63225,
                "name" => "Pendidikan Kepelatihan Olahraga",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '6')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 63325,
                "name" => "Pendidikan Jasmani",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '6')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 70125,
                "name" => "Penelitian dan Evaluasi Pendidikan",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '7')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 70126,
                "name" => "Penelitian dan Evaluasi Pendidikan",
                "degree_id" => Degree::where('code', '=', '6')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '7')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 70225,
                "name" => "Pendidikan Teknologi dan Kejuruan",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '7')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 70226,
                "name" => "Pendidikan Teknologi dan Kejuruan",
                "degree_id" => Degree::where('code', '=', '6')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '7')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 70326,
                "name" => "Ilmu Pendidikan",
                "degree_id" => Degree::where('code', '=', '6')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '7')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 70426,
                "name" => "Manajemen Pendidikan",
                "degree_id" => Degree::where('code', '=', '6')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '7')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 70526,
                "name" => "Ilmu Pendidikan Bahasa",
                "degree_id" => Degree::where('code', '=', '6')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '7')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 70626,
                "name" => "Pendidikan Dasar",
                "degree_id" => Degree::where('code', '=', '6')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '7')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 70726,
                "name" => "Pendidikan Kimia",
                "degree_id" => Degree::where('code', '=', '6')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '7')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 80224,
                "name" => "Pendidikan Administrasi Perkantoran",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '8')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 80324,
                "name" => "Pendidikan Akuntansi",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '8')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 80424,
                "name" => "Pendidikan Ekonomi",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '8')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 80814,
                "name" => "Manajemen",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '8')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 80933,
                "name" => "Akuntansi",
                "degree_id" => Degree::where('code', '=', '3')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '8')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 81033,
                "name" => "Pemasaran",
                "degree_id" => Degree::where('code', '=', '3')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '8')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 81133,
                "name" => "Administrasi Perkantoran",
                "degree_id" => Degree::where('code', '=', '3')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '8')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 81214,
                "name" => "Akuntansi",
                "degree_id" => Degree::where('code', '=', '4')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '8')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => Str::uuid()->toString(),
                "code" => 81925,
                "name" => "Pendidikan Ekonomi",
                "degree_id" => Degree::where('code', '=', '5')->first()->id,
                "faculty_id" => Faculty::where('code', '=', '8')->first()->id,
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ];

        foreach (array_chunk($data, 1000) as $t) {
            StudyProgram::insert($t);
        }
    }
}
