#!/usr/bin/env sh

set -e

container_mode=${CONTAINER_MODE:-"server"}

if [ ${container_mode} = "server" ]; then
    php artisan octane:status
elif [ ${container_mode} = "horizon" ]; then
    php artisan horizon:status
elif [ ${container_mode} = "reverb" ]; then
    supervisorctl status reverb:reverb_00
elif [ ${container_mode} = "scheduler" ]; then
    supervisorctl status scheduler:scheduler_00
elif [ ${container_mode} = "worker" ]; then
    supervisorctl status worker:worker_00
else
    echo "Container mode mismatched."
    exit 1
fi
