#!/usr/bin/env sh

# Taken from https://github.com/exaco/laravel-octane-dockerfile

set -e

container_mode=${CONTAINER_MODE:-"server"}
run_migrations=${RUN_MIGRATIONS:-"false"}
run_seeders=${RUN_SEEDERS:-"false"}

init() {
    echo "Container mode: $container_mode"

    if [ "${run_migrations}" = "true" ]; then
        echo "Running migrations database ..."
        php "${ROOT}/artisan" migrate --isolated --seed --force
    fi

    if [ "${run_seeders}" = "true" ]; then
        echo "Running seeders database ..."
        php "${ROOT}/artisan" db:seed --force
    fi

    ln -s "${ROOT}/storage/app/local/public" "${ROOT}/static/public"

    php "${ROOT}/artisan" optimize:clear; \
    php "${ROOT}/artisan" optimize;
}

if [ "$1" != "" ]; then
    exec "$@"
elif [ "${container_mode}" = "server" ]; then
    init
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.server.conf
elif [ "${container_mode}" = "horizon" ]; then
    init
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.horizon.conf
elif [ "${container_mode}" = "reverb" ]; then
    init
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.reverb.conf
elif [ "${container_mode}" = "scheduler" ]; then
    init
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.scheduler.conf
elif [ "${container_mode}" = "worker" ]; then
    if [ -z "${WORKER_COMMAND}" ]; then
        echo "WORKER_COMMAND is undefined."
        exit 1
    fi
    init
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.worker.conf
else
    echo "Container mode mismatched."
    exit 1
fi
