name: Laravel Release

on:
  push:
    branches:
      - master

jobs:
  release_production:
    name: Release web to production
    if: startsWith(github.event.head_commit.message, 'release-production:')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Deploy to production with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            eval "$(ssh-agent -s)"
            ssh-add .ssh/id_rsa_hello_infinite_deployer
            cd public_html/hello.infiniteuny.id
            php artisan down
            git stash
            git pull
            composer install
            php artisan migrate --force
            php artisan optimize
            php artisan up
